server:
  port: 7011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/git-db
    username: root
    password: mysql25

topic:
  git-loaded: git-load-topic