server:
  port: 7013

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/latest-version-db
    username: root
    password: mysql25

topic:
  latest-version-loaded: latest-version-load-topic