server:
  port: 7000

spring:
  application:
    name: service-config-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jagdish9/service-config-repo
          default-label: main
          clone-on-start: true

logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG